### ISSUE TITLE
Can't get "Feature Type" to work

### ISSUE THREAD

**Issue by Hellhound1** [db0/pythorhead#41]
Trying to use the following code to get a post to be featured to local community:

` lemmy.post.feature(post_id, True, feature_type=FeatureType.Local)`

However this throws the error
`NameError: name 'FeatureType' is not defined`

I can't seem to find a way to get this to work - am I missing something or is this a bug?

**Comment by db0** [comment]
Did you import FeatureType?

**Comment by Hellhound1** [comment]
I am an idiot. Thank you.
