### ISSUE TITLE
[Enhancement] Method to purge a community

### ISSUE THREAD

**Issue by XIRGO** [db0/pythorhead#42]
It would be great to add a method to purge a community or user.

## Community Admin purge
* https://join-lemmy.org/api/interfaces/AdminPurgeCommunity.html
* https://join-lemmy.org/api/interfaces/AdminPurgeCommunityView.html

## User Admin purge
* https://join-lemmy.org/api/interfaces/AdminPurgePerson.html
* https://join-lemmy.org/api/interfaces/AdminPurgePersonView.html

**Comment by db0** [comment]
Fixed in #44
