### ISSUE TITLE
Marking a PM as read

### ISSUE THREAD

**Issue by Demigodrick** [db0/pythorhead#45]
Is it possible to mark a received PM as read? 

This is the api link but I dont think this is implemented in Pythorhead?

https://join-lemmy.org/api/interfaces/MarkPrivateMessageAsRead.html

Edit: Code you need at the bottom of private_message.py is:

```
def mark_as_read(self, private_message_id: int, read: bool) -> Optional[dict]:
 

        Mark a Private Message as read

        Args:
            private_message_id (int)
            read (bool)

        Returns:
            Optional[dict]: private message data if successful
        """

        mark_as_read_private_message = {
            "private_message_id": private_message_id,
            "read": read,
        }
        return self._requestor.api(Request.POST, "/private_message/mark_as_read", json=mark_as_read_private_message)
```

**Comment by Demigodrick** [comment]
@db0 sorry for the ping, quite new to github so not sure how to do a PR but this is the code for this if you're happy to add it in. I've tested and it works fine.

**Comment by db0** [comment]
Hah ok I'll handle it. Thanks
