### ISSUE TITLE
Dependency on loguru

### ISSUE THREAD

**Issue by chris-y** [db0/pythorhead#6]
After I installed using pip, Pythorhead complained about a missing dependency, "loguru". Pip should have been aware of this dependency and installed it automatically.

`from loguru import logger` in auth.py

**Comment by db0** [comment]
Hm, it's in our requirements.txt, so not sure why it wasn't taken into account. To be fair I don't typically publish on pypi. I'll take a look

**Comment by tanitna** [comment]
Having specific versions in the requirements is probably going to cause problems too.

**Comment by db0** [comment]
It shouldn't. If anything it should prevent unexpected breakage

**Comment by Falmarri** [comment]
Unless someone else pulls in a different library that depends on a different version.

I also suggest using poetry https://python-poetry.org/

**Comment by db0** [comment]
Fixed in #10
