### ISSUE TITLE
ERROR:pythorhead.requestor:Error encountered while Request.POST: relation "activity" does not exist

### ISSUE THREAD

**Issue by 8ullyMaguire** [db0/pythorhead#67]
When trying to interact with an account on a defederated instance requestor logs this error but I don't have a way to handle it. I would need a return value or a raised exception.

**Comment by db0** [comment]
Sorry I'm trying to understand what causes this. What exactly are you trying to do?

**Comment by 8ullyMaguire** [comment]
I've tried upvote/downvote on a user from a defederated instance.
