### ISSUE TITLE
A community needs to be searched before it can be discovered

### ISSUE THREAD

**Issue by 8ullyMaguire** [db0/pythorhead#68]
I think the default behavior should be searching for the community if it isn't discovered and then try to discover it again:

```python
def discover_or_search_community(lemmy: Lemmy, community_name: str) -> int:
    # Try to discover the community
    community_id = discover_community(lemmy, community_name)

    # If the community is not discovered, search for it and then discover it
    if not community_id:
        search_result = search(lemmy, community_name)
        if search_result:
            community_id = discover_community(lemmy, search_result["community_name"])

    return community_id

def discover_community(lemmy: Lemmy, community_name: str) -> int:
    community_id: int = lemmy.discover_community(community_name)
    if not community_id:
        raise Exception(f"Failed to discover community {community_name}")
    return community_id

def search(lemmy: Lemmy, community_name: str) -> Dict[str, Any]:
    res: Dict[str, Any] = lemmy.search(community_name)
    return res
```

**Comment by db0** [comment]
Good idea. Feel free to send a PR if you have the time.

**Comment by 8ullyMaguire** [comment]
Actually I think I was wrong when suggesting this. When searching for a community you need to use the url of the community from the original instance for example `https://lemmy.ml/c/technology` and it takes quite a bit of time to find a community, like a minute or so, by searching only for the community name I don't think you can discover a new community. I will try now to confirm.

**Comment by db0** [comment]
It should work both ways. However it does look like community searching is recently kinda bugged or just extremely slow. I've been haivng trouble to discover new communities as well.
