### ISSUE TITLE
Set timeout for requests

### ISSUE THREAD

**Issue by dandroid126** [db0/pythorhead#75]
Rarely a request will not respond. When this happens, it takes about 15 minutes to time out. When making my own requests, I can reduce the impact of this by setting the timeout argument to requests.get() or whichever method. 

My bot updates posts every 30 seconds with real time data for sports games, so having a thread get stuck for 15 minutes hurts the usability of the bot. 

Below are the relevant logs for when this happens. Notice the time difference between when the request is started and when it finally times out.

```
Sep 24 19:55:02 nhl-gameday-bot [1]: [DEBUG] Starting new HTTPS connection (1): lemmy.ca:443
Sep 24 20:10:54 nhl-gameday-bot [1]: [ERROR] Error encountered while Request.PUT on endpoint /post: HTTPSConnectionPool(host='lemmy.ca', port=443): Max retries exceeded with url: /api/v3/post (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
```

**Comment by dandroid126** [comment]
Ideally I would like to be able to pass a timeout parameter into lemmy.post.edit() and have that be given to requests. It looks like this functionality is almost there. In requestor.py, the api function takes in `**kwargs` and passes that along to requests. However post.edit() doesn't seem to accept `**kwargs`.

**Comment by db0** [comment]
good point. I'll let you define a global request timeout

**Comment by dandroid126** [comment]
That works for me. Thanks.

**Comment by dandroid126** [comment]
Any news on this? I just had my bot get stuck for about 2 hours before I noticed and killed it and restarted it.
