### ISSUE TITLE
Issue with 0.19 authentication

### ISSUE THREAD

**Issue by Demigodrick** [db0/pythorhead#84]
After updating to 0.19, I'm getting errors on api calls. It appears to log in OK to begin with, but then any admin call produces the error

INFO - Connected succesfully to Lemmy v0.19.0 instance https://lemmy.zip

ERROR - Error encountered while Request.GET on endpoint /post/report/list: {"error":"incorrect_login"}
ERROR - Error encountered while Request.GET on endpoint /comment/report/list: {"error":"incorrect_login"}

I know the authentication has changed with 0.19 - nothing has changed in my code so I'm wondering if its to do with the auth change?

**Comment by db0** [comment]
Almost certainly. I need to find the time to work on the change for pythorhead to handle 0.19
