### ISSUE TITLE
Return post id on create?

### ISSUE THREAD

**Issue by chris-y** [db0/pythorhead#9]
Is it possible to return the post id after creating a thread/post?
Currently the library returns true on success, it would be better to return 0/None on failure and post_id on success.
All the other methods need a post id as parameter, but there's no easy way of getting one from a newly created post.
I checked the Lemmy API documentation but I can't fathom out what it returns!

**Comment by chris-y** [comment]
Thanks, on 0.2.0 the id is returned as ["post_view"]["post"]["id"] - which is a bit of a mouthful but it works!

**Comment by db0** [comment]
Fixed in #10

**Comment by db0** [comment]
Yes it returns the whole post json in case you need any other info from it
