### ISSUE TITLE
Reading and dealing with reports

### ISSUE THREAD

**Issue by chris-y** [db0/pythorhead#99]
Are there plans to add the API for looking at reports (I think these are GetReportCount and PostReportView)?

Or are they already present and I've missed them?

**Comment by M4rtineski** [comment]
This functionality is needed to make bots on different instances, make them moderators in different communities and crawl the reports into matrix room because the report federation is pretty damn bad and it would make moderating easier.

**Comment by db0** [comment]
I've typically added endpoints I've needed or someone sent in a PR. I can try to look into adding these. If you can point me to the API endpoints you need exactly, it will help

**Comment by db0** [comment]
Note there is `report_list()` and `resolve_report()` in post and comment
